# Generated by Django 5.0.1 on 2024-02-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
